//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreadsChallenge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {

        public Person() {  }

        public int id { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string suffix { get; set; }
        public string address_line1 { get; set; }
        public string address_line2 { get; set; }
        public string city { get; set; }
        public string state_province_name { get; set; }
        public string country_region_name { get; set; }
        public string postal_code { get; set; }
        public string phone_number { get; set; }
        public DateTime birth_date { get; set; }
        public string education { get; set; }
        public string occupation { get; set; }
        public string gender { get; set; }
        public string marital_status { get; set; }
        public int home_owner_flag { get; set; }
        public int number_cars_owned { get; set; }
        public int number_children_at_home { get; set; }
        public int total_children { get; set; }
        public int yearly_income { get; set; }
    }
}
